"""NIFTY 50 + selected NIFTY Next 50 liquid equities."""

NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "ITC",
    "SBIN", "BHARTIARTL", "KOTAKBANK", "LT", "AXISBANK", "ASIANPAINT", "MARUTI",
    "TITAN", "SUNPHARMA", "BAJFINANCE", "HCLTECH", "WIPRO", "ULTRACEMCO",
    "NTPC", "POWERGRID", "M&M", "TATAMOTORS", "ADANIENT", "JSWSTEEL", "TATASTEEL",
    "NESTLEIND", "BAJAJFINSV", "TECHM", "INDUSINDBK", "HINDALCO", "COALINDIA",
    "GRASIM", "CIPLA", "DRREDDY", "EICHERMOT", "BPCL", "DIVISLAB", "APOLLOHOSP",
    "HEROMOTOCO", "BRITANNIA", "TATACONSUM", "SBILIFE", "HDFCLIFE", "ADANIPORTS",
    "LTIM", "BAJAJ-AUTO", "PIDILITIND", "ONGC",
]

NIFTY_NEXT_50 = [
    "ABB", "ADANIGREEN", "AMBUJACEM", "BANKBARODA", "BEL", "BERGEPAINT",
    "BOSCHLTD", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR", "DABUR", "DLF",
    "GAIL", "GODREJCP", "HAL", "HAVELLS", "HDFCAMC", "ICICIPRULI", "ICICIGI",
    "INDIGO", "IOC", "IRCTC", "JINDALSTEL", "LUPIN", "MARICO", "MOTHERSON",
    "NAUKRI", "PEL", "PFC", "PIIND", "PNB", "RECLTD", "SHREECEM", "SIEMENS",
    "SRF", "TATAPOWER", "TORNTPHARM", "TRENT", "TVSMOTOR", "UPL", "VEDL",
    "VOLTAS", "ZOMATO", "ZYDUSLIFE", "DMART", "JIOFIN", "MAXHEALTH",
    "NHPC", "POLYCAB",
]

BASE_UNIVERSE = list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50))
